# Generated by Django 4.2.4 on 2023-08-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandOwners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Land Owner",
                "verbose_name_plural": "Land Owners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LandTenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_name",
                    models.CharField(max_length=255, verbose_name="Land Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "images",
                    models.FileField(
                        blank=True, upload_to="lands/images/", verbose_name="Images"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "catalogueNumber",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Catalogue Number"
                    ),
                ),
                (
                    "volume",
                    models.CharField(blank=True, max_length=50, verbose_name="Volume"),
                ),
                (
                    "folio",
                    models.CharField(blank=True, max_length=50, verbose_name="Folio"),
                ),
                (
                    "fourmil",
                    models.CharField(blank=True, max_length=50, verbose_name="Fourmil"),
                ),
                (
                    "milinch",
                    models.CharField(blank=True, max_length=50, verbose_name="Milinch"),
                ),
                (
                    "portion",
                    models.CharField(blank=True, max_length=50, verbose_name="Portion"),
                ),
                (
                    "type_of_tenement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Freehold", "Freehold"),
                            ("Leasehold", "Leasehold"),
                            ("Customary", "Customary"),
                            ("Commercial", "Commercial"),
                            ("State or Public Land", "State or Public Land"),
                        ],
                        max_length=255,
                        verbose_name="Type of Tenement",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "lease_holder",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.company",
                        verbose_name="Lease Holder",
                    ),
                ),
                (
                    "llg",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.locallevelgovernment",
                        verbose_name="LLG",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Tenement",
                "verbose_name_plural": "Land Tenements",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="LandTenementSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_date",
                    models.DateField(blank=True, verbose_name="Survey Date"),
                ),
                (
                    "surveyor_name",
                    models.CharField(max_length=255, verbose_name="Surveyor Name"),
                ),
                (
                    "land_tenement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="land_tenement_surveys_by_land_tenement",
                        to="land.landtenement",
                        verbose_name="Land Tenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Tenement Survey",
                "verbose_name_plural": "Land Tenement Surveys",
                "ordering": ["-survey_date"],
            },
        ),
        migrations.CreateModel(
            name="MiningTenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_name",
                    models.CharField(max_length=255, verbose_name="Land Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "images",
                    models.FileField(
                        blank=True, upload_to="lands/images/", verbose_name="Images"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "catalogueNumber",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Catalogue Number"
                    ),
                ),
                (
                    "volume",
                    models.CharField(blank=True, max_length=50, verbose_name="Volume"),
                ),
                (
                    "folio",
                    models.CharField(blank=True, max_length=50, verbose_name="Folio"),
                ),
                (
                    "fourmil",
                    models.CharField(blank=True, max_length=50, verbose_name="Fourmil"),
                ),
                (
                    "milinch",
                    models.CharField(blank=True, max_length=50, verbose_name="Milinch"),
                ),
                (
                    "portion",
                    models.CharField(blank=True, max_length=50, verbose_name="Portion"),
                ),
                (
                    "type_of_tenement",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Special Mining Lease (SML)",
                                "Special Mining Lease (SML)",
                            ),
                            (
                                "Lease for Mining Purpose (LMP)",
                                "Lease for Mining Purpose (LMP)",
                            ),
                            (
                                "Lease Compensation Arrangement (LCA)",
                                "Lease Compensation Arrangement (LCA)",
                            ),
                            ("Exploration Lease", "Exploration Lease"),
                        ],
                        max_length=255,
                        verbose_name="Type of Tenement",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "lease_holder",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.company",
                        verbose_name="Lease Holder",
                    ),
                ),
                (
                    "llg",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.locallevelgovernment",
                        verbose_name="LLG",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining Tenement",
                "verbose_name_plural": "Mining Tenements",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MiningTenementSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_date",
                    models.DateField(blank=True, verbose_name="Survey Date"),
                ),
                (
                    "surveyor_name",
                    models.CharField(max_length=255, verbose_name="Surveyor Name"),
                ),
                (
                    "mininig_tenement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_tenement_surveys_by_mining_tenement",
                        to="land.miningtenement",
                        verbose_name="Mining Tenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining Tenement Survey",
                "verbose_name_plural": "Mining Tenement Surveys",
                "ordering": ["-survey_date"],
            },
        ),
        migrations.CreateModel(
            name="MiningTenementSurveyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "mining_tenement_survey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_tenemenet_survey_points_by_mining_tenement_survey",
                        to="land.miningtenementsurvey",
                        verbose_name="Mining Tenement Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining Tenement Survey Point",
                "verbose_name_plural": "Mining Tenement Survey Points",
            },
        ),
        migrations.CreateModel(
            name="MiningTenementRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Online Payment", "Online Payment"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "payer_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Payer Details"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "mining_tenement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_tenement_rentals_by_mining_tenement",
                        to="land.miningtenement",
                        verbose_name="Mining Tenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining Tenement Rental",
                "verbose_name_plural": "Mining Tenement Rentals",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="MiningTenementAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Acquisition Date"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "duration_years",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the lease in years.",
                        null=True,
                        verbose_name="Duration (Term)",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase price in PNG kina",
                        max_digits=15,
                        verbose_name="Purchace Price (PGK)",
                    ),
                ),
                (
                    "rental_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rental amount in PNG kina",
                        max_digits=15,
                        verbose_name="Rental Amount (PGK)",
                    ),
                ),
                (
                    "rental_due_date",
                    models.DateField(blank=True, verbose_name="Rental Due Date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "mining_tenement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_tenement_acquisition_by_mining_tenement",
                        to="land.miningtenement",
                        verbose_name="Mining Tenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining Tenement Acquisition",
                "verbose_name_plural": "Mining Tenement Acquisitions",
            },
        ),
        migrations.CreateModel(
            name="LandTenementSurveyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "land_tenement_survey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="land_tenemenet_survey_points_by_land_tenement_survey",
                        to="land.landtenementsurvey",
                        verbose_name="Land Tenement Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Tenement Survey Point",
                "verbose_name_plural": "Land Tenement Survey Points",
            },
        ),
        migrations.CreateModel(
            name="LandTenementRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount Paid"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Online Payment", "Online Payment"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "payer_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Payer Details"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "land_tenement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="land_tenement_rentals_by_land_tenement",
                        to="land.landtenement",
                        verbose_name="Land Tenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Tenement Rental",
                "verbose_name_plural": "Land Tenement Rentals",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="LandTenementAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Acquisition Date"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "duration_years",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the lease in years.",
                        null=True,
                        verbose_name="Duration (Term)",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase price in PNG kina",
                        max_digits=15,
                        verbose_name="Purchace Price (PGK)",
                    ),
                ),
                (
                    "rental_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rental amount in PNG kina",
                        max_digits=15,
                        verbose_name="Rental Amount (PGK)",
                    ),
                ),
                (
                    "rental_due_date",
                    models.DateField(blank=True, verbose_name="Rental Due Date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "land_tenement",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="land_tenement_acquisition_by_land_tenement",
                        to="land.landtenement",
                        verbose_name="Land Tenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Tenement Acquisition",
                "verbose_name_plural": "Land Tenement Acquisitions",
            },
        ),
    ]
