# Generated by Django 4.2.4 on 2023-08-27 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_context", "0004_dwelling_trust_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dwelling",
            name="dwelling_number",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Dwelling Number",
            ),
        ),
    ]
