# Generated by Django 4.2.4 on 2023-08-27 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_bank_bank_initials_alter_bank_bank_name"),
        ("community_context", "0006_alter_householdbankaccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdbankaccount",
            name="account_number",
            field=models.CharField(
                help_text="Enter No Account if household dont' have bank account.",
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Account Name",
            ),
        ),
        migrations.AlterField(
            model_name="householdbankaccount",
            name="bank_initials",
            field=models.ForeignKey(
                help_text="Choose Nil if household don't have bank account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="household_bank_accounts_by_bank_initials",
                to="main.bank",
                verbose_name="Bank Initials",
            ),
        ),
        migrations.AlterField(
            model_name="householdbankaccount",
            name="branch",
            field=models.CharField(
                blank=True,
                help_text="Leave blank if household don't have bank account.",
                max_length=255,
                verbose_name="Branch",
            ),
        ),
        migrations.AlterField(
            model_name="householdbankaccount",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Dormant", "Dormant"), ("Nil", "Nil")],
                help_text="Choose Nil if household don't have bank account.",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
