# Generated by Django 4.2.4 on 2023-08-27 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "community_context",
            "0007_alter_householdbankaccount_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdbankaccount",
            name="account_name",
            field=models.CharField(
                help_text="Enter No Account if household dont' have bank account.",
                max_length=255,
                verbose_name="Account Name",
            ),
        ),
        migrations.AlterField(
            model_name="householdbankaccount",
            name="account_number",
            field=models.CharField(
                help_text="Enter ten digits of 9 if household dont' have bank account.",
                max_length=10,
                validators=[
                    django.core.validators.MinValueValidator(8),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Account Number",
            ),
        ),
    ]
