# Generated by Django 4.2.4 on 2023-08-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("Bank of South Pacific", "Bank of South Pacific"),
                            ("Westpac Bank", "Westpac Bank"),
                            (
                                "Australia and New Zealand Bank",
                                "Australia and New Zealand Bank",
                            ),
                            ("Kina Bank", "Kina Bank"),
                        ],
                        max_length=255,
                        verbose_name="Bank Name",
                    ),
                ),
                (
                    "bank_initials",
                    models.CharField(
                        choices=[
                            ("BSP", "BSP"),
                            ("WPC", "WPC"),
                            ("ANZ", "ANZ"),
                            ("KB", "KB"),
                        ],
                        max_length=3,
                        verbose_name="Bank initials",
                    ),
                ),
                (
                    "account_number_length",
                    models.PositiveIntegerField(verbose_name="Account Number Length"),
                ),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LocalLevelGovernment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llgs_by_districts",
                        to="main.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLG",
                "verbose_name_plural": "LLGs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provinces_by_country",
                        to="main.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrustRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Trust Region",
                "verbose_name_plural": "Trust Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="villages_by_district",
                        to="main.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "llg",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages_by_llg",
                        to="main.locallevelgovernment",
                        verbose_name="LLG",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="villages_by_province",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Villages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrustVillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trustvillage_by_district",
                        to="main.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "llg",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trustvillage_by_llg",
                        to="main.locallevelgovernment",
                        verbose_name="LLG",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trustvillage_by_province",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
                (
                    "trust_region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_villages_by_region",
                        to="main.trustregion",
                        verbose_name="Trust Region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Village",
                "verbose_name_plural": "Trust Villages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tribes_by_province",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tribe",
                "verbose_name_plural": "Tribes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="locallevelgovernment",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llgs_by_province",
                to="main.province",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="districts_by_province",
                to="main.province",
            ),
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clans_by_district",
                        to="main.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "llg",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clans_by_llg",
                        to="main.locallevelgovernment",
                        verbose_name="LLG",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clans_by_province",
                        to="main.province",
                        verbose_name="Province",
                    ),
                ),
                (
                    "tribe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clans_by_tribe",
                        to="main.tribe",
                        verbose_name="Tribe",
                    ),
                ),
                (
                    "trust_village",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clans_by_trust_village",
                        to="main.trustvillage",
                    ),
                ),
                (
                    "village",
                    models.ManyToManyField(
                        blank=True, related_name="clans_by_village", to="main.village"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clan",
                "verbose_name_plural": "Clans",
                "ordering": ["name"],
            },
        ),
    ]
