# Generated by Django 4.2.4 on 2023-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bank_initials",
            field=models.CharField(
                choices=[
                    ("BSP", "BSP"),
                    ("WPC", "WPC"),
                    ("ANZ", "ANZ"),
                    ("KB", "KB"),
                    ("Nil", "Nil"),
                ],
                max_length=3,
                verbose_name="Bank initials",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("Bank of South Pacific", "Bank of South Pacific"),
                    ("Westpac Bank", "Westpac Bank"),
                    (
                        "Australia and New Zealand Bank",
                        "Australia and New Zealand Bank",
                    ),
                    ("Kina Bank", "Kina Bank"),
                    ("Nil", "Nil"),
                ],
                max_length=255,
                verbose_name="Bank Name",
            ),
        ),
    ]
