# Generated by Django 4.2.4 on 2023-08-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("community_benefit", "0004_communitybenefitallocation_trust_region"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllicationDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_allocation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_distributions_by_benefit_allocation",
                        to="community_benefit.communitybenefitallocation",
                        verbose_name="Benefit Allocation",
                    ),
                ),
                (
                    "benefit_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_distributions_by_benefit_category",
                        to="community_benefit.communitybenefitcategory",
                        verbose_name="Benefit Category",
                    ),
                ),
                (
                    "trust_region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_distributions_by_trust_region",
                        to="main.trustregion",
                        verbose_name="Trust Region",
                    ),
                ),
                (
                    "trust_village",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_distributions_by_trust_village",
                        to="main.trustvillage",
                        verbose_name="Trust Village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation Distribution",
                "verbose_name_plural": "Allocation Distributions",
            },
        ),
    ]
