# Generated by Django 4.2.4 on 2023-08-27 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_benefit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communitybenefitcategory",
            options={
                "verbose_name": "Community Benefit Category",
                "verbose_name_plural": "Community Benefit Categories",
            },
        ),
        migrations.AddField(
            model_name="communitybenefitcategory",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2023),
                ],
                verbose_name="Year",
            ),
        ),
    ]
