# Generated by Django 4.2.4 on 2023-08-27 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community_benefit", "0002_alter_communitybenefitcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitybenefitcategory",
            name="year",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2023),
                ],
                verbose_name="Year",
            ),
        ),
        migrations.CreateModel(
            name="CommunityBenefitAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in PNG kina.",
                        max_digits=12,
                        verbose_name="Amount (PGK)",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2023),
                        ],
                        verbose_name="Year",
                    ),
                ),
                (
                    "community_benefit_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_benefit_allocations_by_communty_benefit_category",
                        to="community_benefit.communitybenefitcategory",
                        verbose_name="Community Benefit Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Benefit Allocation",
                "verbose_name_plural": "Community Benefit Allocations",
            },
        ),
    ]
